// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export  default  {
    "graphqlEndpoint": "https://epgdpm7wxvcahmkhhtjk4pzelu.appsync-api.us-east-2.amazonaws.com/graphql",
    "region": "us-east-2",
    "authenticationType": "API_KEY",
    "apiKey": "da2-ekzcspvcenfdzjaz5zvadb4sg4",
};

